### ISSUE TITLE
Wrong variable wind_gust_speed

### ISSUE THREAD

**Issue by slimr** [weigu1/wheather_ecovitt_2_mqtt#1]
https://github.com/weigu1/wheather_ecovitt_2_mqtt/blob/59c9ea20b377e7cc6398aa13cdd4d5c73b281c03/weather_ecowitt_2_mqtt.py#L131
https://github.com/weigu1/wheather_ecovitt_2_mqtt/blob/59c9ea20b377e7cc6398aa13cdd4d5c73b281c03/weather_ecowitt_2_mqtt.py#L131

**Comment by weigu1** [comment]
Thanks :)
It was even e second var wrong (rain_total).
